### ISSUE TITLE
Notification Error on Windows 

### ISSUE THREAD

**Issue by hdetavernier** [ursjoss/check_fileage#1]
Hi,

Thanks for your work.
I would like to use it on Windows Server with Python2.7 but I noticied that the return code is different from Linux environnment.
Example:

On Windows
check_fileage.py -f C:\Temp\test\test.txt -x -w 5 -c 30 -d C
Unknow: system Error - Unable to access the file test.txt

On Linux:
./check_fileage.py -f /tmp/test/test -x -w 1440 -c 2880 -d M
FILE CRITICAL: test does not exist.

Would it possible to unify both Linux and Windows retur code error?

**Comment by ursjoss** [comment]
Hi @hdetavernier 

Thanks for your interest in using my version of check_fileage.py.

The message you get on windows is not the equivalent of the message you see on linux (in your example). The script fails evaluating the file and thus falls into the exception handler on line 166 and specifically into branch on line 182.

I have not used the script on windows before, but now installed python-2.7.14 to test the issue. Unfortunately I have not been able to reproduce the issue.

If the file does not exist:

```
python.exe check_fileage.py -f C:\Temp\test\test.txt -x -w 5 -c 30 -d C
FILE CRITICAL: test.txt does not exist.
```

If the file exists but is it's age is within the warn period:

```
python.exe check_fileage.py -f C:\Temp\test\test.txt -x -w 5 -c 30 -d C
FILE WARNING: test.txt has a created (NOT *NIX) date of Fri 06 Apr/2018 15:42
```

Can you add some debug statements between line 139 and 165 to see where the script fails?

**Comment by hdetavernier** [comment]
Hi,
the problem is solved and your tool works very fine both on Linux and windows.
I took the original version of the file instead of your version.

Thanks a lot.
